### PR TITLE
UI upd

### PR DESCRIPTION
**Pull request by user2589**
[Screenshot](http://i.imgur.com/vSgybMF.png)

### CODE REVIEW

**Comment by mansuleman** [comment]
```
======================================================================
FAIL: test_scpi2widgets (easy_phi.tests.scpi2widgets_test.BasicWidgetsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "easy_phi/tests/scpi2widgets_test.py", line 40, in test_scpi2widgets
    "Received widgets: {widgets}".format(widgets=widgets)
AssertionError: Empty module configuration resulted in non-empty widgets.                         Received widgets: ['container.append(\n"<input type=\'text\'     name=\'module_scpi_cmd_"+slot+"\' id=\'module_scpi_cmd_"+slot+"\'>"+\n"<input     type=\'button\' value=\'Send SCPI\' id=\'module_scpi_submit_"+slot+"\'>");\n$("#module_scpi_submit_" + slot).click(function(){\nscpi($("#module_scpi_cmd_"+slot).val());\n});']

----------------------------------------------------------------------
```

**Comment by user2589** [comment]
This is a test error, underlying code is correct. Somehow it does not get test configuration file and uses system default, resulting in configuration is different from expected.  Last time it took couple hours to fix it, and this time it was promising to take at least the same long. Because of release, I think we should accept this test fail and I will fix it later

**Comment by mansuleman** [comment]
UI looks much better, but can be still improved. Given that we need to release "Ship it"

**Comment by rezniknn** [comment]
Looks good to me. Ship it

**Pull request merged**
